// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.

function require(script) {
    $.ajax({
        method: "POST",
        url: script,
        dataType: "script"
    });
}

require('/biblioteki/bootstrap/js/transition.js')
require('/biblioteki/bootstrap/js/alert.js')
require('/biblioteki/bootstrap/js/button.js')
require('/biblioteki/bootstrap/js/carousel.js')
require('/biblioteki/bootstrap/js/collapse.js')
require('/biblioteki/bootstrap/js/dropdown.js')
require('/biblioteki/bootstrap/js/modal.js')
require('/biblioteki/bootstrap/js/tooltip.js')
require('/biblioteki/bootstrap/js/popover.js')
require('/biblioteki/bootstrap/js/scrollspy.js')
require('/biblioteki/bootstrap/js/tab.js')
require('/biblioteki/bootstrap/js/affix.js')
require('/biblioteki/bootstrap/js/wysiwyg.js')
require('/biblioteki/bootstrap/js/wysiwyg-editor.js')
require('/biblioteki/bootstrap/js/notify.js')
